# Generated by Django 2.2.28 on 2022-05-05 00:03

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_library', '0002_documentplugin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'document category Translation'},
        ),
        migrations.AlterModelOptions(
            name='documenttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'document Translation'},
        ),
        migrations.AlterField(
            model_name='documentcategorytranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='documentcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='document_library.DocumentCategory'),
        ),
        migrations.AlterField(
            model_name='documentplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='document_library_documentplugin', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='document_library.Document'),
        ),
    ]
